### ISSUE TITLE
Past Events Feature Flaw

### ISSUE THREAD

**Issue by marclzh** [marclzh/pe#6]
Events with dates in the past can be added.

![image.png](https://raw.githubusercontent.com/marclzh/pe/main/files/8624c421-a705-43da-b36a-49634b74313b.png)

- task event m/Alex Yeoh d/Finish user guide t/2021-12-31

**Comment by nus-se-script** [comment]
# Team's Response
A potential use case for this is for a user to record an event that has passed.

For example, the user might have used another application to record down events, but upon migration to TaskBook, wants the events in the past to be recorded here too.

Another example, the user might have forgotten to record down an event until it is over. However, the date of the event is important and the user feels that it should be noted down. Thus, the user can note it down after the event has passed for the sake of recording.
# Items for the Tester to Verify
## :question: Issue response

Team chose [`response.Rejected`]

- [x] I disagree

**Reason for disagreement:** Although it might be true that users might be migrating from another application, there is no validation check for events that are set to be in the past. This could lead to users mistakenly setting the wrong event date, e.g., putting in the wrong month/day without noticing, and letting the event pass without knowing, which I believe is still an issue that could arise in this scenario. Thus I still believe that this is a feature flaw, but is of low severity. One way this could be addressed is by putting a warning if the event is in the past.

-------------------
